### ISSUE TITLE
Search only looks in first sidebar folder

### ISSUE THREAD

**Issue by zao** [amireh/SwitchScript#1]
If you have several folders in the sidebar, only the first one will be searched for the file, thanks to `root = self.window.folders()[0]`.

Better would be to look in the same folder that the current file can be found in, or in all folders if that fails.

**Comment by amireh** [comment]
Done.

The script will now look in all folders, prioritizing the root folder of the current open file (IF it's open), otherwise it will settle for the first possible match it could find in any of the other open folders (in the order that the folders were opened in the window session).

Closing.

**Comment by amireh** [comment]
Actually, I'm re-opening until you test it out and see if it suits your needs. Keep me updated!

**Comment by amireh** [comment]
I'll take the silence as a sign of everything being fine, so, re-closing.
